export const ActionTypes = {
  SET_PLAYERS: "SET_PLAYERS",
  RND_CARDS: "RND_CARDS",
  ADD_TO_SCORE1: "ADD_TO_SCORE1",
  ADD_TO_SCORE2: "ADD_TO_SCORE2",
  SET_ACTIVATE_CHECKER: "SET_ACTIVATE_CHECKER"
}